In [3]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 20)

print("Libraries imported successfully!")

Libraries imported successfully!

# Financial Sales Performance Analysis

## Objective

The objective of this project is to analyze the financial sales dataset to identify business trends, evaluate product and regional performance, understand customer segments, and generate actionable insights through Python, SQL, Excel, and Tableau/PowerBI.

---

### Business Questions

1. Which country generates the highest sales?
2. Which products are the most profitable?
3. Which customer segment contributes the most revenue?
4. How do discounts affect profit?
5. Which months perform best?
6. Which products should the company focus on?
7. What recommendations can improve profitability?

In [4]:
df = pd.read_excel("../data/week4_data.xlsx")

In [5]:
df.head()

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Germany,Carretera,NaN,1513.0,3,350,529550.0,0.0,529550.0,393380.0,136170.0,2014-12-01,12,December,2014
1,Government,Germany,Paseo,NaN,1006.0,10,350,352100.0,0.0,352100.0,261560.0,90540.0,2014-06-01,6,June,2014
2,Government,Canada,Paseo,NaN,1725.0,10,350,603750.0,0.0,603750.0,448500.0,155250.0,2013-11-01,11,November,2013
3,Government,Germany,Paseo,NaN,1513.0,10,350,529550.0,0.0,529550.0,393380.0,136170.0,2014-12-01,12,December,2014
4,Government,Germany,Velo,NaN,1006.0,120,350,352100.0,0.0,352100.0,261560.0,90540.0,2014-06-01,6,June,2014

In [6]:
df.shape

(700, 16)

In [7]:
df.columns

Index(['Segment', 'Country', 'Product', 'Discount Band', 'Units Sold',
       'Manufacturing Price', 'Sale Price', 'Gross Sales', 'Discounts',
       'Sales', 'COGS', 'Profit', 'Date', 'Month Number', 'Month Name',
       'Year'],
      dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Segment              700 non-null    str
 1   Country              700 non-null    str
 2   Product              700 non-null    str
 3   Discount Band        647 non-null    str
 4   Units Sold           700 non-null    float64
 5   Manufacturing Price  700 non-null    int64
 6   Sale Price           700 non-null    int64
 7   Gross Sales          700 non-null    float64
 8   Discounts            700 non-null    float64
 9   Sales                700 non-null    float64
 10  COGS                 700 non-null    float64
 11  Profit               700 non-null    float64
 12  Date                 700 non-null    datetime64[us]
 13  Month Number         700 non-null    int64
 14  Month Name           700 non-null    str
 15  Year                 700 non-null    int64
dtypes: datetime64[us](1), float64(6), int64(4), str(5)
memory usage: 87.6 KB

In [9]:
df.describe()

,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Year
count,700.000000,700.000000,700.000000,7.000000e+02,700.000000,7.000000e+02,700.000000,700.000000,700,700.000000,700.000000
mean,1608.294286,96.477143,118.428571,1.827594e+05,13150.354629,1.696091e+05,145475.211429,24133.860371,2014-04-28 21:36:00,7.900000,2013.750000
min,200.000000,3.000000,7.000000,1.799000e+03,0.000000,1.655080e+03,918.000000,-40617.500000,2013-09-01 00:00:00,1.000000,2013.000000
25%,905.000000,5.000000,12.000000,1.739175e+04,800.320000,1.592800e+04,7490.000000,2805.960000,2013-12-24 06:00:00,5.750000,2013.750000
50%,1542.500000,10.000000,20.000000,3.798000e+04,2585.250000,3.554020e+04,22506.250000,9242.200000,2014-05-16 12:00:00,9.000000,2014.000000
75%,2229.125000,250.000000,300.000000,2.790250e+05,15956.343750,2.610775e+05,245607.500000,22662.000000,2014-09-08 12:00:00,10.250000,2014.000000
max,4492.500000,260.000000,350.000000,1.207500e+06,149677.500000,1.159200e+06,950625.000000,262200.000000,2014-12-01 00:00:00,12.000000,2014.000000
std,867.427859,108.602612,136.775515,2.542623e+05,22962.928775,2.367263e+05,203865.506118,42760.626563,NaN,3.377321,0.433322

In [10]:
df.duplicated().sum()
df.isnull().sum()

Segment                 0
Country                 0
Product                 0
Discount Band          53
Units Sold              0
Manufacturing Price     0
Sale Price              0
Gross Sales             0
Discounts               0
Sales                   0
COGS                    0
Profit                  0
Date                    0
Month Number            0
Month Name              0
Year                    0
dtype: int64

In [11]:
df.sample(5, random_state=42)

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
158,Government,Germany,Carretera,Medium,663.0,3,20,13260.0,1193.40,12066.60,6630.0,5436.60,2014-05-01,5,May,2014
500,Small Business,France,Amarilla,High,853.0,260,300,255900.0,25590.00,230310.00,213250.0,17060.00,2014-12-01,12,December,2014
396,Midmarket,Mexico,Velo,Medium,2861.0,120,15,42915.0,2145.75,40769.25,28610.0,12159.25,2014-01-01,1,January,2014
155,Government,Germany,Amarilla,Medium,1520.0,260,20,30400.0,2432.00,27968.00,15200.0,12768.00,2014-11-01,11,November,2014
321,Channel Partners,United States of America,Amarilla,NaN,1953.0,260,12,23436.0,0.00,23436.00,5859.0,17577.00,2014-04-01,4,April,2014

In [12]:
for col in df.columns:
    print(f"{col}: {df[col].nunique()}")

Segment: 5
Country: 5
Product: 6
Discount Band: 3
Units Sold: 510
Manufacturing Price: 6
Sale Price: 7
Gross Sales: 550
Discounts: 515
Sales: 559
COGS: 545
Profit: 557
Date: 16
Month Number: 12
Month Name: 12
Year: 2

In [13]:
df["Discount Band"].value_counts(dropna=False)

Discount Band
High      245
Medium    242
Low       160
NaN        53
Name: count, dtype: int64

In [14]:
df[df["Discount Band"].isna()][["Discount Band", "Discounts"]].head(10)

    Discount Band  Discounts
0             NaN        0.0
1             NaN        0.0
2             NaN        0.0
3             NaN        0.0
4             NaN        0.0
5             NaN        0.0
6             NaN        0.0
100           NaN        0.0
101           NaN        0.0
102           NaN        0.0